<?php
session_start();
$prompt =$_SESSION["imgprompt"];    
if (isset($_POST['submit'])) {

    if($prompt == "bbqinvite"){
        $finalprompt = "Design a stunning image that brings to life the spirit of a lively BBQ party! The scene should feature a picturesque outdoor setting, complete with a beautifully set picnic table adorned with an assortment of grilled dishes - juicy steaks, tender barbecue ribs, and charred vegetable skewers. The BBQ grill should be emitting mouthwatering smoke, adding to the inviting atmosphere. Surround the scene with a backdrop of lush greenery, tall shade trees, and perhaps a glimpse of a serene lake or a cozy bonfire where friends and family are gathered, laughing and enjoying each other's company"; 
        $occasion = "BBQ Party";
        $thrower = $_POST['thrower'];
        $person = $_POST['person'];
        $date = $_POST['date'];
        $venue = $_POST['venue'];
        $time = $_POST['time'];
        $imgsrc = "assets/bbqinvite.png";
    }
    elseif($prompt == "engagementinvite"){
        $occasion = "Engagement";
        $finalprompt= "generate me a image of a couple exchanging rings";
        $bride = $_POST['bride'];
        $groom = $_POST['groom'];
        $person = $_POST['person'];
        $date = $_POST['date'];
        $venue = $_POST['venue'];
        $time = $_POST['time'];
        $imgsrc = "assets/engagment.jpeg";
    }
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/images/generations');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
        "prompt" => $finalprompt,
        "n" => 1,
        "size" => "1024x1024"
    ]));

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer 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';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    $data = json_decode($result, true);
    $final_url = $data['data'][0]['url'];

    
}
?>


<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BBQ invitation Card</title>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500&display=swap" rel="stylesheet" />
    <!-- Stylesheet -->
    <link rel="stylesheet" href="styles/spin.css" />

    <style>

    </style>

</head>

<body>
    <div class="container">
        <div class="card">
            <!-- Front Side-->
            <div class="front center">
                <div class="element">
                    <img src=<?php echo "".$imgsrc."";?> height="520px" width="410px">
                    <div class="text">
                        <p style="color: white;">Dear <?php echo $person?></p>
                        <p style="color: white;">you have been invited to <?php
                        if($prompt == "engagementinvite"){
                            echo "".$bride."'s and ".$groom."'s ";
                        }
                        echo $occasion;
                        if($prompt == "bbqinvite"){
                            echo "by ".$thrower;
                        }
                        ?></p>
                        <p style="color: white;">venue <?php echo $venue;?></p>
                        <p style="color: white;">at <?php echo $time;?></p>
                        <p style="color: white;">on <?php echo $date;?>
                        <?php echo "please be there your precense matters" ?></p>
                    </div>
                </div>
            </div>
            <!-- Back Side-->
            <div class="back center">
                <div class="dalleimg">
                    <?php echo '<img src="' . $final_url . '" class="img-fluid" alt="Generated Image">';?>
                </div>
            </div>
        </div>
    </div>
</body>