<?php
$title = "Greeting";
require_once  'includes/header.php';

?>

<?php

if (isset($_POST['submit'])) {
    $prompt = $_POST['generate'];

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/images/generations');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
        "prompt" => $prompt,
        "n" => 1,
        "size" => "1024x1024"
    ]));

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer yourkeyhere';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    $data = json_decode($result, true);
    $final_url = $data['data'][0]['url'];

    echo '<img src="' . $final_url . '" class="img-fluid" alt="Generated Image">';
}
?>


<form method="post" action="flip.php" enctype="multipart/form-data">

    <!-- Here goes the Name input -->
    <div class="form-group">
        <label for="yourName" class="form-label">Your Name</label>
        <input required type="text" class="form-control" id="yourName" name="yourName">
    </div>
    <br />

    <!-- Here goes the name of the person whom we are going ti greet input -->
    <div class="form-group">
        <label for="name" class="form-label">Name of the person to be greeted</label>
        <input required type="text" class="form-control" id="name" name="name">
    </div>
    <br />

    <!-- Here goes the relation of the person with the person to be greeted input -->
    <div class="form-group">
        <label for="relation" class="form-label">Relation with the person</label>
        <input required type="text" class="form-control" id="relation" name="relation">
    </div>
    <br />

    <!-- Here goes the occasion input -->
    <div class="form-group">
        <label for="occasion" class="form-label">Occasion</label>
        <select class="form-control" id="occasion" name="occasion">
            <option>Select One</option>
            <option>Birthday</option>
            <option>Wedding Anniversary</option>
            <option>Baby Shower</option>
            <option>Party Invitations</option>
        </select>
    </div>
    <br />

    <!-- Here goes the personaltiy traits of the person to be greeted input -->
    <div class="form-group">
        <label for="personality" class="form-label">Personality/Character</label>
        <input required type="text" class="form-control" id="personality" name="personality">
        <small id="generate" class="form-text">Enter all the personality traits of the person to be greeted..</small>
    </div>
    <br />

    <!-- Here goes the DALL E image input -->
    <div class="form-group">
        <label for="generate" class="form-label">Start with a detailed description</label>
        <input required type="text" class="form-control" id="generate" name="generate">
        <small id="generate" class="form-text">We recommed that enter the image description according to the occasion..</small>
    </div>
    <br />

    <!-- Here goes the Submit button input -->
    <div class="d-grid gap-2">
        <button type="submit" name="submit" onclick="window.location.href='flip.php'" class="btn btn-primary btn-block">Submit</button>
    </div>

</form>
<!-- 
<script>
    function previewImage(event) {
        const fileInput = event.target;
        const file = fileInput.files[0];

        if (file) {
            const reader = new FileReader();

            reader.onload = function(e) {
                const imagePreview = document.getElementById("imagePreview");
                const img = document.createElement("img");
                img.src = e.target.result;
                img.classList.add("img-thumbnail");
                imagePreview.innerHTML = "";
                imagePreview.appendChild(img);
            };

            reader.readAsDataURL(file);
        }
    }
</script> -->

<br />
<br />
<br />
<br />
<br />

<?php require_once  'includes/footer.php'; ?>